### ISSUE TITLE
change font

### ISSUE THREAD

**Issue by abdulhdr1** [gustavo-fior/home#1]
the website is currently using an awful-looking font, please change it, you can find some free to use ones at [google fonts](https://fonts.google.com/) and add them to tailwind by [extending the default theme](https://tailwindcss.com/docs/font-family#customizing-the-default-font)

**Comment by gustavo-fior** [comment]
right, u think it looks good now?  https://github.com/gustavo-fior/home/commit/68c97708083e364be63cda864b2acfbb11c60e66

**Comment by abdulhdr1** [comment]
Yep! Much better, very nice
