### ISSUE TITLE
custom domain

### ISSUE THREAD

**Issue by abdulhdr1** [gustavo-fior/home#2]
buy a domain and [assign it to your vercel account](https://vercel.com/docs/concepts/projects/domains/add-a-domain) or (as I'd recommend) buy it in cloudflare and deploy the website using cloudflare pages with the next.js preset

**Comment by gustavo-fior** [comment]
will u pay for my domain?

**Comment by abdulhdr1** [comment]
I can pay for it, but I'll ask for a refund when mind gets funded

**Comment by gustavo-fior** [comment]
LGTM!
